version: '3'

networks:
  moodle:

services:
  moodle:
    build: ./docker/moodle
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./siteroot:/var/www/html
    depends_on:
      - mailhog
    networks:
      - moodle
  db:
    image: postgres:9.6
    environment:
      PHP_EXTENTION_XDEBUG: 1
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle_user
    volumes:
      - 'db:/var/lib/postgresql/data'
    networks:
      - moodle
  test-db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle_user
    volumes:
      - 'testdb:/var/lib/postgresql/data'
    networks:
      - moodle
  mailhog:
    image: mailhog/mailhog
    ports:
      - "127.0.0.1:1025:8025"
    networks:
      - moodle
volumes:
    db:
    testdb:

