version: "3"
services:
  # # # # # # # # # # # # # # #
  # Moodle service
  # # # # # # # # # # # # # # #
  moodle:
    build: ./docker/moodle
    security_opt:
      - seccomp:unconfined
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./siteroot:/siteroot

  # # # # # # # # # # # # # # #
  # Database services
  # # # # # # # # # # # # # # #
  db:
    image: postgres:latest
    restart: always
    environment:
      PHP_EXTENTION_XDEBUG: 1
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle_user
    volumes:
      - 'db:/var/lib/postgresql'
  test-db:
    image: postgres:latest
    restart: always
    environment:
      PHP_EXTENTION_XDEBUG: 1
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle_user
    volumes:
      - 'testdb:/var/lib/postgresql'
  cache-db:
    image: postgres:latest
    restart: always
    environment:
      PHP_EXTENTION_XDEBUG: 1
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle_user
    volumes:
      - 'cachedb:/var/lib/postgresql'

  # # # # # # # # # # # # # # #
  # Additonal services
  # # # # # # # # # # # # # # #
  maximal-pool:
    image: unihalle/maximapool:stack-2017121800
    restart: always
    environment:
        - MAXIMAPOOL_ADMIN_PASSWORD=password
    ports:
        - "127.0.0.1:8765:8080"
    volumes:
        - "./volumes/pool.conf:/opt/maximapool/pool.conf:ro"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "moodle@moodle.com"
      PGADMIN_DEFAULT_PASSWORD: "moodle"
    ports:
      - 127.0.0.1:8088:80

  redis:
    image: redis
    restart: always
    volumes:
      - 'redis:/var/lib/redis'
volumes:
  db:
  testdb:
  cachedb:
  redis: